# Generated by Django 2.2.28 on 2023-05-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=100)),
            ],
        ),
    ]
